sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t popluharp/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t popluharp/multi-client ./client
  - docker build -t popluharp/multi-nginx ./nginx
  - docker build -t popluharp/multi-server ./server
  - docker build -t popluharp/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push popluharp/multi-client
  - docker push popluharp/multi-nginx
  - docker push popluharp/multi-server
  - docker push popluharp/multi-worker
